name: billyalarm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  # removed flutter_tts (replaced with native ringtone playback)
  android_alarm_manager_plus: ^5.0.0
  timezone: ^0.9.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/billyalarm.png"
  web:
    generate: true
    image_path: "assets/billyalarm.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:

  uses-material-design: true
